spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  profiles:
    default: local

  mail:
    host: smtp.gmail.com
    port : 587
    username: ${MAIL_SENDER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    clean-disabled: true

imdb:
  baseUrl: https://datasets.imdbws.com/
  basicsGz: title.basics.tsv.gz
  ratingsGz: title.ratings.tsv.gz

execution:
  tConstSelectSize: 500
  movieInsertSize: 500
  ratingInsertSize: 500
  timeoutSeconds: 180
  maxPreviousYears: 2
  maxRatingDays: 1000
  recipient: ${MAIL_RECIPIENT}
  summaryIntervalDays: 10





